services:
  gateway:
    build:
      context: gateway
      dockerfile: ./dockerfile
    env_file:
      - gateway/.env
    container_name: gateway
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
    ports:
      - '9999:8000'
    networks:
      - default
    depends_on:
      - 'auth'
      - 'license'

  auth:
    build:
      context: auth
      dockerfile: ./dockerfile
    env_file:
      - auth/.env
    container_name: authentication_service
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
    networks:
      - default
    depends_on:
      - users_db
    expose:
      - '8030'

  users_db:
    image: postgres:15
    container_name: users_db
    expose:
      - '5432'
    networks:
      - default
    env_file:
      - auth/.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    volumes:
      - users_data:/var/lib/postgresql/data

  license:
    build:
      context: license
      dockerfile: ./dockerfile
    env_file:
      - license/.env
    container_name: license_service
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
    networks:
      - default
    depends_on:
      - license_db
    expose:
      - '8060'

  license_db:
    image: postgres:15
    container_name: license_db
    expose:
      - '5433'
    env_file:
      - license/.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
      - PGPORT=${DB_PORT}
    volumes:
      - licenses_data:/var/lib/postgresql/data

volumes:
  users_data:
  licenses_data:
