services:
  web:
    build:
      context: ../license-generator-web
      dockerfile: ./dockerfile
    env_file:
      - ./.env
    restart: unless-stopped
    container_name: web
    ports:
      - '10000:80'
    networks:
      - default
    depends_on:
      - gateway

  gateway:
    build:
      context: gateway
      dockerfile: ./Dockerfile
    env_file:
      - gateway/.env
    restart: unless-stopped
    container_name: gateway
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
    ports:
      - '9999:8000'
    networks:
      - default
    depends_on:
      - auth
      - license

  auth:
    build:
      context: auth
      dockerfile: ./Dockerfile
    env_file:
      - auth/.env
    restart: unless-stopped
    container_name: auth
    command: sh -c "alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0"
    networks:
      - default
    depends_on:
      - users_db
    ports:
      - '8030:8000'
    volumes:
      - ./auth/logs:/auth/logs

  users_db:
    image: postgres:15
    restart: unless-stopped
    container_name: users_db
    ports:
      - '5432:5432'
    networks:
      - default
    env_file:
      - auth/.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    volumes:
      - users_data:/var/lib/postgresql/data

  license:
    build:
      context: license
      dockerfile: ./Dockerfile
    env_file:
      - license/.env
    restart: unless-stopped
    container_name: license
    command: sh -c "alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0"
    networks:
      - default
    depends_on:
      - license_db
    ports:
      - '8060:8000'
    volumes:
      - ./license/logs:/license/logs
      - ./license/files/licenses:/license/files/licenses
      - ./license/files/machine_digest_files:/license/files/machine_digest_files

  license_db:
    image: postgres:15
    restart: unless-stopped
    container_name: license_db
    ports:
      - '5433:5432'
    networks:
      - default
    env_file:
      - license/.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    volumes:
      - licenses_data:/var/lib/postgresql/data

volumes:
  users_data:
  licenses_data:
  license_files:

networks:
  default:
    name: adv_license
