version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    ports:
      - "5432:5432"
    networks:
      - default
    env_file:
      - .env-non-dev
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - "9999:8000"
    networks:
      - default
    depends_on:
      - db
